In [2]:
import pandas as pd

**read_csv() :-** Load data

In [3]:
toyota_data = pd.read_csv("Data/car_sales/toyota_sales_data.csv")

In [27]:
toyota_data.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed

In [28]:
sales_reps_data = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/sales_reps_data.csv")

In [29]:
sales_reps_data.head()

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active
3,4,Robert,Lopez,robert.lopez@toyota.com,-8631,11/21/20,South,Active
4,5,Steven,Wilson,steven.wilson@toyota.com,-6958,3/17/22,West,Active

---

Info() :- Shows DataFrame structure, columns, data types, and missing values

describe():- Shows statistical summary of "numerical" columns

* info()      → INFORMATION about structure
* describe()  → DESCRIPTION / statistics of data

In [32]:
toyota_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sale_id         5000 non-null   int64
 1   sale_rep_id     5000 non-null   int64
 2   sale_date       5000 non-null   str
 3   car_model       5000 non-null   str
 4   sale_amount     5000 non-null   float64
 5   commission_pct  3726 non-null   float64
 6   sale_status     5000 non-null   str
dtypes: float64(2), int64(2), str(3)
memory usage: 273.6 KB

In [31]:
toyota_data.describe()

           sale_id  sale_rep_id   sale_amount  commission_pct
count  5000.000000  5000.000000   5000.000000     3726.000000
mean   2500.500000    10.531600  32979.708214        0.033725
std    1443.520003     5.787824   7420.301088        0.012503
min       1.000000     1.000000  20000.940000        0.020000
25%    1250.750000     6.000000  27259.710000        0.020000
50%    2500.500000    11.000000  32613.765000        0.030000
75%    3750.250000    16.000000  38751.005000        0.050000
max    5000.000000    20.000000  49995.680000        0.050000

---

**Shape** is attribute, so we dont use "()"

In [11]:
toyota_data.shape

(5000, 7)

---

**columns:-** to get the column

In [12]:
toyota_data.columns

Index(['sale_id', 'sale_rep_id', 'sale_date', 'car_model', 'sale_amount',
       'commission_pct', 'sale_status'],
      dtype='str')

---

**tolist():-** used to convert it into pyhton list

In [13]:
toyota_data.columns.tolist()

['sale_id',
 'sale_rep_id',
 'sale_date',
 'car_model',
 'sale_amount',
 'commission_pct',
 'sale_status']

---

**dtypes**:- to get datatypes

In [14]:
toyota_data.dtypes

sale_id             int64
sale_rep_id         int64
sale_date             str
car_model             str
sale_amount       float64
commission_pct    float64
sale_status           str
dtype: object

---

In [15]:
help(pd.read_csv)

Help on function read_csv in module pandas:

read_csv(
    filepath_or_buffer: FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str],
    *,
    sep: str | None | lib.NoDefault = <no_default>,
    delimiter: str | None | lib.NoDefault = None,
    header: int | Sequence[int] | None | Literal['infer'] = 'infer',
    names: Sequence[Hashable] | None | lib.NoDefault = <no_default>,
    index_col: IndexLabel | Literal[False] | None = None,
    usecols: UsecolsArgType = None,
    dtype: DtypeArg | None = None,
    engine: CSVEngine | None = None,
    converters: Mapping[HashableT, Callable] | None = None,
    true_values: list | None = None,
    false_values: list | None = None,
    skipinitialspace: bool = False,
    skiprows: list[int] | int | Callable[[Hashable], bool] | None = None,
    skipfooter: int = 0,
    nrows: int | None = None,
    na_values: Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None = None,
    keep_default_na: bool = True,
    na_filter: bool = True,
    skip_blank_lines: bool = True,
    parse_dates: bool | Sequence[Hashable] | None = None,
    date_format: str | dict[Hashable, str] | None = None,
    dayfirst: bool = False,
    cache_dates: bool = True,
    iterator: bool = False,
    chunksize: int | None = None,
    compression: CompressionOptions = 'infer',
    thousands: str | None = None,
    decimal: str = '.',
    lineterminator: str | None = None,
    quotechar: str = '"',
    quoting: int = 0,
    doublequote: bool = True,
    escapechar: str | None = None,
    comment: str | None = None,
    encoding: str | None = None,
    encoding_errors: str | None = 'strict',
    dialect: str | csv.Dialect | None = None,
    on_bad_lines: str = 'error',
    low_memory: bool = True,
    memory_map: bool = False,
    float_precision: Literal['high', 'legacy', 'round_trip'] | None = None,
    storage_options: StorageOptions | None = None,
    dtype_backend: DtypeBackend | lib.NoDefault = <no_default>
) -> DataFrame | TextFileReader
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. ``sep=None`` detects
        the separator from the first valid row of the file with Python's builtin
        sniffer tool, ``csv.Sniffer``; it is supported only by the Python parsing
        engine, which will be used automatically.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names:
        if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.

        When inferred from the file contents, headers are kept distinct from
        each other by renaming duplicate names with a numeric suffix of the form
        ``".{count}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
        Empty headers are named ``"Unnamed: {i}"`` or ``
        "Unnamed: {i}_level_{level}"``
        in the case of MultiIndex columns.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
        Column(s) to use as row label(s), denoted either by column labels or column
        indices.  If a sequence of labels or indices is given,
        :class:`~pandas.MultiIndex`
        will be formed for the row labels.

        Note: ``index_col=False`` can be used to force pandas to *not* use the first
        column as the index, e.g., when you have a malformed file with delimiters at
        the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either
        by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s).
        If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion. Specify a ``defaultdict`` as input where
        the default determines the ``dtype``
        of the columns which are not explicitly
        listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster,
        while the python engine
        is currently more feature-complete. Multithreading
        is currently only supported by
        the pyarrow engine. Some features of the "pyarrow" engine
        are unsupported or may not work correctly.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition
        to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive
        variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False``
        otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
        Refers to the number of data rows in the returned DataFrame, excluding:

        * The header row containing column names.
        * Rows before the header row, if ``header=1`` or larger.

        Example usage:

        * To read the first 999,999 (non-header) rows:
          ``read_csv(..., nrows=999999)``

        * To read rows 1,000,000 through 1,999,999:
          ``read_csv(..., skiprows=1000000, nrows=999999)``

    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable},
        optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict``
        passed, specific
        per-column ``NA`` values.  By default the following values
        are interpreted as
        ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
        representations of missing data.
    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values``
          are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``,
        the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, None, list of Hashable, default None
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index.
        * ``None``. Behaves like ``True`` if ``date_format`` is specified.
        * ``list`` of ``int`` or names.
          e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates and/or times when
        used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"`` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
          time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
          and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data.
        If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only
        one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
        ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for
        Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
        2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
        only fields containing special
        characters are quoted (e.g., characters defined
        in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
        When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
        whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
        field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are:

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is
          encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when
          they are encountered.
        - Callable, function that will process a single bad line.
            - With ``engine='python'``, function with signature
              ``(bad_line: list[str]) -> list[str] | None``.
              ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new ``list`` of strings with
              more elements than
              expected, a ``ParserWarning`` will be emitted while
              dropping extra elements.
            - With ``engine='pyarrow'``, function with signature
              as described in pyarrow documentation: `invalid_row_handler
              <https://arrow.apache.org/docs/python
              /generated/pyarrow.csv.ParseOptions.html
              #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

        .. versionchanged:: 2.2.0

            Callable for ``engine='pyarrow'``

    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set ``False``, or specify the type with the ``dtype`` parameter.
        Note that the entire file is read into a single :class:`~pandas.DataFrame`
        regardless, use the ``chunksize`` or ``iterator``
        parameter to return the data in
        chunks. (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for ``filepath_or_buffer``, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.
    float_precision : {'high', 'legacy', 'round_trip'}, optional

---

In [16]:
difference=pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv")
difference.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed

In [17]:
toyota_data = pd.read_csv(
    "/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv",
    delimiter = ",",
    header = 0,
    # TO specify which index is header
    names = ['sale_id','sale_rep_id','sale_date','car_model','sale_amount','commission_pct','sale_status'],
     #we can use "names", to create header if we dont have one
    index_col ="sale_id" 
    # To change the index(basically comes in seperate column 0), "to sales_id"
)

In [18]:
toyota_data.head(5)

,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
sale_id,,,,,,
1,16,2024-11-18,Tundra,44496.88,0.05,Completed
2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
3,5,2024-11-03,Corolla,20275.08,NaN,Completed
4,20,2024-11-06,Corolla,20068.93,NaN,Completed
5,1,2024-11-26,Tundra,49811.99,0.03,Completed

---

In [19]:
toyota_data.shape

(5000, 6)

there will be millions of data, so we cant load all of it, so we load it into chunks

In [20]:
chunk_size = 100 #define chunk size

toyota_chunk_reader = pd.read_csv(
    "/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv",
    chunksize=chunk_size
    #assigining chunk_size to "chunksize"
    #or we explicitly mention like chunksize=1000
)

In [21]:
print(type(toyota_chunk_reader)) 
#since we have used "chunksize", it becomes the type of "TextFileReader" from pandas
print(type(toyota_data))

<class 'pandas.io.parsers.readers.TextFileReader'>
<class 'pandas.DataFrame'>

In [ ]:
toyota_chunk_reader.head()
toyota_chunk_reader.shape
#since we are using chunksize, it converts into "TextFileReader" not "Dataframe",
#so we can't perform dataframe operations like head or shape etc.,
#it throws error

In [23]:
#toyota_chunk_reader becomes genetator, in python we use loop(for) through the generater and process the data
for toyota_chunk in toyota_chunk_reader:
    print(toyota_chunk.shape)

(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)

**Note: Since the toyota_chunk_reader is processed, if we want perfrom a new operation, we need to run the read_csv code again**

In [24]:
for toyota_chunk in toyota_chunk_reader:
    print(toyota_chunk.head())

---

**Use Case :-** Apply simple business rules, which is calculate commision amount(sale*commision percentage)

In [63]:
toyota_data= pd.read_csv(
    "/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv",
    delimiter=","
)

In [ ]:
toyota_data["commission_amount"] = (toyota_data["sale_amount"] * toyota_data["commission_pct"]).fillna(0).round(2)
#fillna(0), converts Null value into "0"
#.round(2), gives exacte "2" decimal point

In [71]:
toyota_data.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,commission_amount
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2224.84
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending,0.00
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed,0.00
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed,0.00
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.36

---

**Exporting or loading back the above modified data(dataframe) to csv**

using ".to_csv" 

syntax:- dataframe_name.to_csv

In [72]:
help(toyota_data.to_csv)

Help on method to_csv in module pandas.core.generic:

to_csv(
    path_or_buf: FilePath | WriteBuffer[bytes] | WriteBuffer[str] | None = None,
    *,
    sep: str = ',',
    na_rep: str = '',
    float_format: str | Callable | None = None,
    columns: Sequence[Hashable] | None = None,
    header: bool | list[str] = True,
    index: bool = True,
    index_label: IndexLabel | None = None,
    mode: str = 'w',
    encoding: str | None = None,
    compression: CompressionOptions = 'infer',
    quoting: int | None = None,
    quotechar: str = '"',
    lineterminator: str | None = None,
    chunksize: int | None = None,
    date_format: str | None = None,
    doublequote: bool = True,
    escapechar: str | None = None,
    decimal: str = '.',
    errors: OpenFileErrors = 'strict',
    storage_options: StorageOptions | None = None
) -> str | None method of pandas.DataFrame instance
    Write object to a comma-separated values (csv) file.

    Parameters
    ----------
    path_or_buf : str, path object, file-like object, or None, default None
        String, path object (implementing os.PathLike[str]), or file-like
        object implementing a write() function. If None, the result is
        returned as a string. If a non-binary file object is passed, it should
        be opened with `newline=''`, disabling universal newlines. If a binary
        file object is passed, `mode` might need to contain a `'b'`.
    sep : str, default ','
        String of length 1. Field delimiter for the output file.
    na_rep : str, default ''
        Missing data representation.
    float_format : str, Callable, default None
        Format string for floating point numbers. If a Callable is given, it takes
        precedence over other numeric formatting parameters, like decimal.
    columns : sequence, optional
        Columns to write.
    header : bool or list of str, default True
        Write out the column names. If a list of strings is given it is
        assumed to be aliases for the column names.
    index : bool, default True
        Write row names (index).
    index_label : str or sequence, or False, default None
        Column label for index column(s) if desired. If None is given, and
        `header` and `index` are True, then the index names are used. A
        sequence should be given if the object uses MultiIndex. If
        False do not print fields for index names. Use index_label=False
        for easier importing in R.
    mode : {'w', 'x', 'a'}, default 'w'
        Forwarded to either `open(mode=)` or `fsspec.open(mode=)` to control
        the file opening. Typical values include:

        - 'w', truncate the file first.
        - 'x', exclusive creation, failing if the file already exists.
        - 'a', append to the end of file if it exists.

    encoding : str, optional
        A string representing the encoding to use in the output file,
        defaults to 'utf-8'. `encoding` is not supported if `path_or_buf`
        is a non-binary file object.

    compression : str or dict, default 'infer'
        For on-the-fly compression of the output data. If 'infer' and
        'path_or_buf' is path-like, then detect compression from the following
        extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        Set to ``None`` for no compression.
        Can also be a dict with key ``'method'`` set to one of
        {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdCompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for faster compression and
        to create a reproducible gzip archive:
        ``compression={'method': 'gzip', 'compresslevel': 1, 'mtime': 1}``.

           May be a dict with key 'method' as compression mode
           and other entries as additional compression options if
           compression mode is 'zip'.

           Passing compression options as keys in dict is
           supported for compression modes 'gzip', 'bz2', 'zstd', and 'zip'.
    quoting : optional constant from csv module
        Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
        then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
        will treat them as non-numeric.
    quotechar : str, default '\"'
        String of length 1. Character used to quote fields.
    lineterminator : str, optional
        The newline character or character sequence to use in the output
        file. Defaults to `os.linesep`, which depends on the OS in which
        this method is called ('\\n' for linux, '\\r\\n' for Windows, i.e.).
    chunksize : int or None
        Rows to write at a time.
    date_format : str, default None
        Format string for datetime objects.
    doublequote : bool, default True
        Control quoting of `quotechar` inside a field.
    escapechar : str, default None
        String of length 1. Character used to escape `sep` and `quotechar`
        when appropriate.
    decimal : str, default '.'
        Character recognized as decimal separator. E.g. use ',' for
        European data.
    errors : str, default 'strict'
        Specifies how encoding and decoding errors are to be handled.
        See the errors argument for :func:`open` for a full list
        of options.

    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib.request.Request`` as header options. For other
        URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
        forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
        details, and for more examples on storage options refer `here
        <https://pandas.pydata.org/docs/user_guide/io.html?
        highlight=storage_options#reading-writing-remote-files>`_.

    Returns
    -------
    None or str
        If path_or_buf is None, returns the resulting csv format as a
        string. Otherwise returns None.

    See Also
    --------
    read_csv : Load a CSV file into a DataFrame.
    to_excel : Write DataFrame to an Excel file.

    Examples
    --------
    Create 'out.csv' containing 'df' without indices

    >>> df = pd.DataFrame(
    ...     [["Raphael", "red", "sai"], ["Donatello", "purple", "bo staff"]],
    ...     columns=["name", "mask", "weapon"],
    ... )
    >>> df.to_csv("out.csv", index=False)  # doctest: +SKIP

    Create 'out.zip' containing 'out.csv'

    >>> df.to_csv(index=False)
    'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'
    >>> compression_opts = dict(
    ...     method="zip", archive_name="out.csv"
    ... )  # doctest: +SKIP
    >>> df.to_csv(
    ...     "out.zip", index=False, compression=compression_opts
    ... )  # doctest: +SKIP

    To write a csv file to a new folder or nested folder you will first
    need to create it using either Pathlib or os:

    >>> from pathlib import Path  # doctest: +SKIP
    >>> filepath = Path("folder/subfolder/out.csv")  # doctest: +SKIP
    >>> filepath.parent.mkdir(parents=True, exist_ok=True)  # doctest: +SKIP
    >>> df.to_csv(filepath)  # doctest: +SKIP

    >>> import os  # doctest: +SKIP
    >>> os.makedirs("folder/subfolder", exist_ok=True)  # doctest: +SKIP
    >>> df.to_csv("folder/subfolder/out.csv")  # doctest: +SKIP

    Format floats to two decimal places:

    >>> df.to_csv("out1.csv", float_format="%.2f")  # doctest: +SKIP

    Format floats using scientific notation:

    >>> df.to_csv("out2.csv", float_format="{:.2e}".format)  # doctest: +SKIP

In [78]:
toyota_data.to_csv(
    "/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_with_commision .csv",
    index= False
                   )
# Creates a new file that we gave at the end of the location "toyota_sales_with_commision .csv"

---

## **pd.concat()**

**pd.concat() combines two or more pandas Series or DataFrames by stacking them vertically or placing them horizontally.**

**1. Vertical concatenation — axis=0**

The rows are stacked one below another. This is the default behavior.

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Arun", "Bala"],
    "Salary": [25000, 30000]
})

df2 = pd.DataFrame({
    "Name": ["Chitra", "Deepak"],
    "Salary": [28000, 32000]
})

result = pd.concat([df1,df2],ignore_index=True)

result

     Name  Salary
0    Arun   25000
1    Bala   30000
2  Chitra   28000
3  Deepak   32000

**2. Horizontal concatenation — axis=1**

The columns are placed side by side, aligning rows by their index.

In [2]:
df1 = pd.DataFrame({
    "Name": ["Arun", "Bala"]
})

df2 = pd.DataFrame({
    "Salary": [25000, 30000]
})

result = pd.concat([df1, df2], axis=1)

print(result)

   Name  Salary
0  Arun   25000
1  Bala   30000

| Feature           | `concat()`                                   | `merge()`                                             |
| ----------------- | -------------------------------------------- | ----------------------------------------------------- |
| Purpose           | Combines tables by stacking or aligning them | Combines tables using matching key columns or indexes |
| Best for          | Appending batches of similar records         | Joining related datasets                              |
| Common parameters | `axis=0` or `axis=1`                         | `on="ID"`, `how="inner"`                              |
| Example use       | Combining January and February sales records | Combining sales data with salesperson details         |

---

## **JSON**

JSON (JavaScript Object Notation) is a text-based format for storing and exchanging structured data. It is commonly used in APIs and data pipelines.

In [1]:
import pandas as pd

employees = [
    {"name": "Arun", "salary": 25000},
    {"name": "Bala", "salary": 30000},
    {"name": "Chitra", "salary": 28000}
]

pd.DataFrame(employees).to_json(
    "employees.json",
    orient="records",
    indent=4
)

In [2]:
df = pd.read_json("employees.json")

print(df)

     name  salary
0    Arun   25000
1    Bala   30000
2  Chitra   28000

---

## **Parquet**
Parquet is a column-oriented binary file format designed for efficient data storage and processing.

Compared with CSV, Parquet often offers:
- Smaller file sizes through compression.
- Efficient reading of selected columns.
- Better integration with tools such as Apache Spark, AWS Athena, and data lakes.

In [1]:

import pandas as pd

df = pd.DataFrame({
    "Name": ["Arun", "Bala", "Chitra"],
    "Salary": [25000, 30000, 28000]
})

df.to_parquet("test.parquet", index=False)

print("Parquet file created successfully!")

result = pd.read_parquet("test.parquet")
print(result)

Parquet file created successfully!
     Name  Salary
0    Arun   25000
1    Bala   30000
2  Chitra   28000

In [10]:
import sys
import pandas as pd
import pyarrow as pa

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("PyArrow:", pa.__version__)

Python: 3.14.7 (v3.14.7:823f0323ee6, Aug  5 2026, 07:07:01) [Clang 21.0.0 (clang-2100.1.1.101)]
Pandas: 3.0.6
PyArrow: 26.0.0